[package]
name = "hello"
version = "0.1.0"
edition = "2018"

[dependencies]
glow = { path = "../../" }

[target.'cfg(not(any(target_arch = "wasm32")))'.dependencies]
glutin = { version = "0.19", optional = true }
sdl2 = { version = "0.32", optional = true }

[features]
default = []
window-sdl2 = ["sdl2", "glow/sdl2"]
window-glutin = ["glutin", "glow/glutin"]

[target.wasm32-unknown-unknown.dependencies]
web-sys = { version = "0.3", features=["console"] }
wasm-bindgen = "0.2"
